version: "3"
services:
    db-user-test:
        image: postgres
        container_name: db-user-test
        environment:
            POSTGRES_PASSWORD: ${DB_PASS}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB}
            DATABASE_URL: ${DB_URL_TEST}
        volumes:
            - ./dbdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - puma-network
    user-service-test:
        container_name: user-service-test
        environment:
            ENVIRONMENT: test
        build:
            context: ../${USER_PATH}/
            dockerfile: test.service.Dockerfile
        ports:
            - "3001:3001"
        depends_on:
            - db-user-test
        volumes:
            - ../${USER_PATH}:/app
            - /app/node_modules
        networks:
            - puma-network

networks:
    puma-network: 