name: CI
on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Copy repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Make env
        run: |
          touch .env
          echo ENVIRONMENT=dev >> .env
          echo DB_URL_TEST=postgres://pumaadmin:pumaadmin@db-test:5432/puma >> .env
          echo DB_USER=pumaadmin >> .env
          echo DB_PASS=pumaadmin >> .env
          echo DB=puma >> .env
          cat .env

      - name: Make test
        run: sudo make test

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
