name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
    - uses: actions/checkout@v3

    - name: Make env
      run: |
        touch .env
        echo ENVIRONMENT=dev >> .env
        echo DB_URL_TEST=postgres://pumaadmin:pumaadmin@db-test:5432/puma >> .env
        echo DB_USER=pumaadmin >> .env
        echo DB_PASS=pumaadmin >> .env
        echo DB=puma >> .env
        cat .env
    - name: Run Tests
      run: sudo make test

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.REPO_TOKEN }}